### ISSUE TITLE
I cannot for the life of me get your source to compile.

### ISSUE THREAD

**Issue by roydukkey** [RaveNoX/NHibernate.HierarchyId#1]

**Comment by RaveNoX** [comment]
Hello,
I forgot to add NuGet.exe into tree, now it fixed.
Please fetch last commit and try to build again.

**Comment by roydukkey** [comment]
Great. That fixed it.

**Comment by roydukkey** [comment]
What are your thoughts on making the query over work directly on Microsoft.SqlServer.Types.SqlHierarchyId. Here I provide a IUserType for mapping to the SqlHierarchyId type. https://github.com/roydukkey/NHiberntate.HierarchyId.UserType

**Comment by RaveNoX** [comment]
Support for IUserType will be in milestone 1.0 (see issue #3 ).
